apiVersion: v1 
kind: Pod 
metadata: 
  name: cm-pod 
spec:
  containers:
  - name: centos-container  
    image: centos:7
    command: ["sleep" , "10000"]
    envFrom:
      - configMapRef:
          name: game-configmap


--- 
# ConfigMap is a placeHolder to host all the common environment variables that are not sensitive  
apiVersion: v1
kind: ConfigMap
metadata:
  name: game-configmap 
data:
  URL: www.thecloudcareers.com 
  MONGODBUSERNAME: admin 
  MONGODBURL: abc.mongo.url 
  RABBITMQ-ENV: dev 
  ENVIRONMENT: dev 
  WORKURL: payment.abc.com 