# Scope of the env is with in the container
apiVersion: v1
kind: Pod
metadata:
  name: centos-pod                      
spec:                              
  containers:                        
  - name: centos-container                   
    image: centos:7
    command: ["sleep" , "10000"] 
    env:
    - name: MONGODB_URL
      value: "mongodb.robot.local"
    - name: MONGODB_USERNAME
      value: "admin"
    - name: ENVIRONMENT
      value: "dev" 
    - name: DEV_CONTACT 
      value: "abc@xyz.com"
    - name: TIMEOUT_INTERVAL
      value: "30"