apiVersion: v1
kind: Pod
metadata:
  name: centos-pod                      
spec:                              
  containers:                        
  - name: centos-container                   
    image: centos:7
    command: ["sleep" , "10000"] 
    envFrom:
      - configMapRef:
          name: game-configmap


--- 

apiVersion: v1
kind: ConfigMap
metadata:
  name: game-configmap
data:
  MONGODB_URL: "mongodb.robot.local"
  MONGODB_USERNAME: "admin"
  MONGODB_PASSWORD: "admin1212"
  ENVIRONMENT: "dev"
  DEV_CONTACT: "abc@xyz.com"
  TIMEOUT_INTERVAL: "30"
  

--- 
apiVersion: v1
kind: Pod
metadata:
  name: nginx                   
spec:                              
  containers:                        
  - name: nginx-container                   
    image: nginx
    envFrom:
      - configMapRef:
          name: game-configmap
