apiVersion: v1
kind: Pod 
metadata: 
  name: secret-pod 
spec:
  containers:
  - name: centos-container  
    image: centos:7
    command: ["sleep" , "10000"]
    envFrom:
      - secretRef:
          name: game-secret 

--- 
# ConfigMap is a placeHolder to host all the common environment variables that are not sensitive  
apiVersion: v1
kind: Secret
metadata:
  name: game-secret 
data:
  MONGODBUSERNAME: YWRtaW4K 
  MONGODBPASSWORD: cGFzc3dvcmQK
