# Creates Replica Set

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest 

# Replicaset's main purpose is to maintain the specified number of puds running at any time!!!

# But the limitations, is Replciaset won't allow you to upgrade from one version to another version.

# You can scale out os scane-in the number of replicas either declaratively or imperatively